name: Deploy to ITU Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clear target directory on ITU server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ITU_SSH_HOST }}
        username: ${{ secrets.ITU_SSH_USERNAME }}
        key: ${{ secrets.ITU_SSH_KEY }}
        port: ${{ secrets.ITU_SSH_PORT }}
        script: |
          rm -rf public_html/*

    - name: Deploy files to ITU server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ITU_SSH_HOST }}
        username: ${{ secrets.ITU_SSH_USERNAME }}
        key: ${{ secrets.ITU_SSH_KEY }}
        port: ${{ secrets.ITU_SSH_PORT }}
        source: "."
        target: "public_html/"
